name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: job-offer-app/package-lock.json
        
    - name: Install dependencies
      run: |
        cd job-offer-app
        npm ci
        
    - name: Build
      run: |
        cd job-offer-app
        npm run build
        
    - name: Copy built files to root
      run: |
        cp -r job-offer-app/dist/* .
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Deploy to GitHub Pages" || exit 0
        git push
